# Generated by Django 5.0.2 on 2025-02-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_notification_notificationpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceagreement',
            name='gafs',
        ),
        migrations.RemoveField(
            model_name='performanceagreement',
            name='kras',
        ),
        migrations.RemoveField(
            model_name='performanceagreement',
            name='objectives',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_on_probation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_persal_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='persal_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_directorate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='admin_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='agreement_reached_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='employee_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='employee_submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='final_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='midyear_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='pmds_administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='supervisor_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='supervisor_reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performanceagreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('PENDING_AGREEMENT', 'Pending Rating Agreement'), ('PENDING_ADMIN_APPROVAL', 'Pending PMDS Administrator Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='KeyResponsibilityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the Key Responsibility Area')),
                ('weighting', models.DecimalField(decimal_places=2, help_text='Weighting out of 100', max_digits=5)),
                ('measurement', models.TextField(help_text='How this KRA will be measured/assessed')),
                ('employee_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Employee self-rating out of 4', max_digits=3, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('supporting_documents', models.FileField(blank=True, upload_to='kra_evidence/%Y/%m/')),
                ('evidence_uploaded_at', models.DateTimeField(auto_now=True)),
                ('supervisor_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Supervisor rating out of 4', max_digits=3, null=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('agreed_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed rating out of 4', max_digits=3, null=True)),
                ('performance_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kras', to='performance.performanceagreement')),
            ],
            options={
                'ordering': ['performance_agreement', '-weighting'],
            },
        ),
    ]
