# Generated by Django 5.0.2 on 2025-02-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_genericassessmentfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1-2', 'Level 1-2'), ('3-5', 'Level 3-5'), ('6-8', 'Level 6-8'), ('9-10', 'Level 9-10'), ('11-12', 'Level 11-12'), ('13', 'Level 13'), ('14', 'Level 14'), ('15', 'Level 15'), ('16', 'Level 16')], max_length=5, unique=True)),
                ('typical_titles', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AlterField(
            model_name='genericassessmentfactor',
            name='factor',
            field=models.CharField(choices=[('GAF1', 'Job knowledge'), ('GAF2', 'Technical skills'), ('GAF3', 'Acceptance of responsibility'), ('GAF4', 'Quality of work'), ('GAF5', 'Reliability'), ('GAF6', 'Initiative'), ('GAF7', 'Communication'), ('GAF8', 'Interpersonal relationships'), ('GAF9', 'Flexibility'), ('GAF10', 'Team work'), ('GAF11', 'Planning and execution'), ('GAF12', 'Leadership'), ('GAF13', 'Delegation and empowerment'), ('GAF14', 'Management of financial resources'), ('GAF15', 'Management of human resources')], max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.salarylevel'),
        ),
    ]
