# Generated by Django 5.0.2 on 2025-02-22 20:39

from django.db import migrations

def update_numeric_levels(apps, schema_editor):
    SalaryLevel = apps.get_model('performance', 'SalaryLevel')
    for salary_level in SalaryLevel.objects.all():
        salary_level.numeric_level = int(salary_level.level.split('-')[0])
        salary_level.save()

def reverse_numeric_levels(apps, schema_editor):
    SalaryLevel = apps.get_model('performance', 'SalaryLevel')
    for salary_level in SalaryLevel.objects.all():
        salary_level.numeric_level = 1
        salary_level.save()

class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_alter_salarylevel_options_salarylevel_numeric_level'),
    ]

    operations = [
        migrations.RunPython(update_numeric_levels, reverse_numeric_levels),
    ]
