# Generated by Django 5.0.2 on 2025-02-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_update_salary_level_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceagreement',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='approver_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='approver_reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch number for HR processing', max_length=50),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='hr_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='hr_reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('APPROVER', 'Approver')], default='EMPLOYEE', max_length=10),
        ),
        migrations.AlterField(
            model_name='performanceagreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('PENDING_AGREEMENT', 'Pending Rating Agreement'), ('PENDING_APPROVER_REVIEW', 'Pending Approver Review'), ('PENDING_HR_REVIEW', 'Pending HR Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_REVISION', 'Returned for Revision')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='salarylevel',
            name='numeric_level',
            field=models.IntegerField(editable=False),
        ),
    ]
