# Generated by Django 5.0.2 on 2025-02-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_add_sample_data'),
        ('performance', '0011_performanceagreement_approver_and_more'),
    ]

    operations = [
    ]
