# Generated by Django 5.0.2 on 2025-02-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_merge_20250222_2316'),
    ]

    operations = [
    ]
