# Generated by Django 5.0.2 on 2025-02-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0014_add_sample_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midyearreview',
            options={'ordering': ['-review_date']},
        ),
        migrations.RemoveField(
            model_name='midyearreview',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='midyearreview',
            name='final_rating',
        ),
        migrations.RemoveField(
            model_name='midyearreview',
            name='self_rating',
        ),
        migrations.RemoveField(
            model_name='midyearreview',
            name='supervisor_rating',
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='employee_overall_comments',
            field=models.TextField(blank=True, help_text="Employee's overall comments on the mid-year review"),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='employee_rating_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='evidence_document',
            field=models.FileField(blank=True, null=True, upload_to='midyear_review_evidence/'),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='supervisor_overall_comments',
            field=models.TextField(blank=True, help_text="Supervisor's overall comments on the mid-year review"),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='supervisor_rating_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midyearreview',
            name='performance_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midyear_reviews', to='performance.performanceagreement'),
        ),
        migrations.CreateModel(
            name='GAFMidYearRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_rating', models.IntegerField(blank=True, choices=[(5, 'Outstanding Performance (5)'), (4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('employee_evidence', models.TextField(blank=True, help_text='Description of evidence for the rating')),
                ('supervisor_rating', models.IntegerField(blank=True, choices=[(5, 'Outstanding Performance (5)'), (4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('gaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.genericassessmentfactor')),
                ('midyear_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaf_ratings', to='performance.midyearreview')),
            ],
        ),
        migrations.CreateModel(
            name='KRAMidYearRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_rating', models.IntegerField(blank=True, choices=[(5, 'Outstanding Performance (5)'), (4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('employee_evidence', models.TextField(blank=True, help_text='Description of evidence for the rating')),
                ('supervisor_rating', models.IntegerField(blank=True, choices=[(5, 'Outstanding Performance (5)'), (4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.keyresponsibilityarea')),
                ('midyear_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kra_ratings', to='performance.midyearreview')),
            ],
        ),
    ]
