# Generated by Django 5.0.2 on 2025-02-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_alter_midyearreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gafmidyearrating',
            name='employee_rating',
            field=models.IntegerField(blank=True, choices=[(4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True),
        ),
        migrations.AlterField(
            model_name='gafmidyearrating',
            name='supervisor_rating',
            field=models.IntegerField(blank=True, choices=[(4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True),
        ),
        migrations.AlterField(
            model_name='kramidyearrating',
            name='employee_rating',
            field=models.IntegerField(blank=True, choices=[(4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True),
        ),
        migrations.AlterField(
            model_name='kramidyearrating',
            name='supervisor_rating',
            field=models.IntegerField(blank=True, choices=[(4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], null=True),
        ),
    ]
