# Generated by Django 5.0.2 on 2025-02-23 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0017_gafmidyearrating_employee_evidence_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='improvementplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='improvementplan',
            name='area_for_development',
        ),
        migrations.RemoveField(
            model_name='improvementplan',
            name='interventions',
        ),
        migrations.RemoveField(
            model_name='improvementplan',
            name='timeline',
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='overall_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_improvement_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='improvementplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ImprovementPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_for_development', models.TextField()),
                ('source_type', models.CharField(choices=[('PA', 'Performance Agreement'), ('MYR', 'Mid-Year Review')], max_length=3)),
                ('source_id', models.IntegerField(help_text='ID of the source object (PA or MYR)')),
                ('interventions', models.TextField(blank=True)),
                ('timeline', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('improvement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.improvementplan')),
                ('source_gaf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.genericassessmentfactor')),
            ],
        ),
    ]
