# Generated by Django 5.0.2 on 2025-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0019_finalreview_gaffinalrating_krafinalrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaffinalrating',
            name='final_review',
        ),
        migrations.RemoveField(
            model_name='krafinalrating',
            name='final_review',
        ),
        migrations.RemoveField(
            model_name='gaffinalrating',
            name='gaf',
        ),
        migrations.RemoveField(
            model_name='krafinalrating',
            name='kra',
        ),
        migrations.AddField(
            model_name='kramidyearrating',
            name='agreed_rating',
            field=models.IntegerField(blank=True, choices=[(4, 'Performance Significantly Above Expectations (4)'), (3, 'Fully Effective Performance (3)'), (2, 'Performance Not Fully Effective (2)'), (1, 'Unacceptable Performance (1)')], help_text='Final agreed rating between employee and supervisor', null=True),
        ),
        migrations.AlterField(
            model_name='improvementplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='improvementplan',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='FinalReview',
        ),
        migrations.DeleteModel(
            name='GAFFinalRating',
        ),
        migrations.DeleteModel(
            name='KRAFinalRating',
        ),
    ]
