# Generated by Django 5.0.2 on 2025-03-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0021_alter_notificationpreference_reminder_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreview',
            name='manager_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalreview',
            name='manager_comments',
            field=models.TextField(blank=True, help_text="Manager's comments on the final review"),
        ),
        migrations.AddField(
            model_name='finalreview',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalreview',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalreview',
            name='supervisor_signoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalreview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('PENDING_SUPERVISOR_SIGNOFF', 'Pending Supervisor Sign-off'), ('PENDING_MANAGER_APPROVAL', 'Pending Manager Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
