# Generated by Django 5.0.2 on 2025-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0022_finalreview_manager_approval_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceagreement',
            old_name='admin_approved_date',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='performanceagreement',
            old_name='agreement_reached_date',
            new_name='manager_approval_date',
        ),
        migrations.RenameField(
            model_name='performanceagreement',
            old_name='admin_comments',
            new_name='manager_comments',
        ),
        migrations.RenameField(
            model_name='performanceagreement',
            old_name='approver_reviewed_date',
            new_name='rejection_date',
        ),
        migrations.RenameField(
            model_name='performanceagreement',
            old_name='hr_reviewed_date',
            new_name='supervisor_signoff_date',
        ),
        migrations.RemoveField(
            model_name='performanceagreement',
            name='approver_comments',
        ),
        migrations.RemoveField(
            model_name='performanceagreement',
            name='hr_comments',
        ),
        migrations.RemoveField(
            model_name='performanceagreement',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='performanceagreement',
            name='rejected_date',
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='manager_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='manager_comments',
            field=models.TextField(blank=True, help_text="Manager's comments on the mid-year review"),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='midyearreview',
            name='supervisor_signoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midyearreview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('PENDING_SUPERVISOR_SIGNOFF', 'Pending Supervisor Sign-off'), ('PENDING_MANAGER_APPROVAL', 'Pending Manager Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='performanceagreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('PENDING_SUPERVISOR_SIGNOFF', 'Pending Supervisor Sign-off'), ('PENDING_MANAGER_APPROVAL', 'Pending Manager Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
