# Generated by Django 5.0.2 on 2025-03-01 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0023_rename_admin_approved_date_performanceagreement_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldevelopmentplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personaldevelopmentplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
