# Generated by Django 5.0.2 on 2025-03-01 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0024_personaldevelopmentplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceagreement',
            name='hr_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='hr_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='hr_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceagreement',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='performanceagreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE_RATING', 'Pending Employee Self-Rating'), ('PENDING_SUPERVISOR_RATING', 'Pending Supervisor Rating'), ('PENDING_SUPERVISOR_SIGNOFF', 'Pending Supervisor Sign-off'), ('PENDING_MANAGER_APPROVAL', 'Pending Manager Approval'), ('PENDING_HR_VERIFICATION', 'Pending HR Verification'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VERIFY', 'Verify'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, help_text='Type of object affected (e.g., PerformanceAgreement)', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=200)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
